### PR TITLE
Parse JSON columns using MultiJson

### PR DESCRIPTION
**Pull request by darkside**
Athens now understands JSON columns :heart: 

# Changes
- Added MultiJson for parsing JSON data when the column type is 'json'

### CODE REVIEW

**Comment by darkside** [comment]
Let me know if you guys would rather not add a dependency to Oj and I'll change to a simpler `JSON.parse`. I figured Oj would be faster when parsing big results :wink:

**Review by beethovenbrandaofilho — APPROVED** [review]

**Comment by cschulte22** [comment]
How are you getting JSON support to work in Athena?  It's not listed as one of the data types in the documentation and we can't get it work with a `CREATE TABLE` statement: https://docs.aws.amazon.com/athena/latest/ug/create-table.html

**Comment by cschulte22** [comment]
Also, you should use `multi_json` instead of `oj`, that leaves the json parsing implementation up to the end user

**Comment by darkside** [comment]
> How are you getting JSON support to work in Athena? It's not listed as one of the data types in the documentation and we can't get it work with a `CREATE TABLE` statement: https://docs.aws.amazon.com/athena/latest/ug/create-table.html

We are using the [PrestoDB JSON functions](https://prestodb.io/docs/current/functions/json.html#json-functions) `json_format` and `json_parse`. 

A query like this will return the column type as `json`:
```
SELECT JSON_PARSE('{"a": 1, "b": 2}');
```

In some places we transform regular transactional DB data into JSON objects by doing something like:
```
JSON_FORMAT(CAST(MAP_FROM_ENTRIES(ARRAY[...]) AS JSON))
```

**Review by NilsonLima — APPROVED** [review]

**Comment by darkside** [comment]
Thanks guys! :heart:

**Pull request merged**
